In [1]:
import tensorflow as tf
import numpy as np

2023-09-09 10:20:22.898313: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-09 10:20:22.934954: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-09 10:20:22.935402: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-09 10:20:23.731206: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


In [3]:
mnist = tf.keras.datasets.mnist

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-09-09 10:20:31.145864: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-09-09 10:20:31.146565: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.0765651 ,  0.39066765, -0.05231803, -1.0432588 , -0.27299565,
         0.01850037,  0.01691864,  0.5195441 , -0.6255169 , -0.2706608 ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.11204901, 0.15339847, 0.09849966, 0.03656577, 0.07899429,
        0.10572819, 0.10556109, 0.17449836, 0.05552616, 0.07917895]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.2468836

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-09-09 10:20:49.118841: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 3s 2ms/step - loss: 0.2956 - accuracy: 0.9131
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1439 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1061 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0866 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0708 - accuracy: 0.9777


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0682 - accuracy: 0.9798 - 304ms/epoch - 971us/step


[0.06817713379859924, 0.9797999858856201]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
p = probability_model(x_test[:5])

In [15]:
p = p.numpy()

In [16]:
np.amin(p)

3.1993397e-14

In [17]:
p

array([[2.44259894e-07, 5.26570387e-09, 2.16524095e-05, 1.01591206e-04,
        3.68805724e-12, 1.13518517e-07, 7.42196614e-13, 9.99869108e-01,
        1.57128071e-07, 7.14559474e-06],
       [1.75591936e-07, 6.20934297e-05, 9.99915242e-01, 1.00861471e-05,
        1.03461287e-13, 2.36756978e-06, 2.08606184e-06, 1.27210102e-12,
        7.96445329e-06, 3.19933966e-14],
       [1.24183123e-06, 9.98672605e-01, 1.07586806e-04, 2.74200775e-05,
        4.91831815e-05, 9.79763172e-06, 9.61964543e-06, 1.02946372e-03,
        9.19365048e-05, 1.14361831e-06],
       [9.99965906e-01, 3.62284820e-11, 1.67431208e-05, 2.67508238e-08,
        4.48792116e-06, 1.94508038e-06, 4.37917424e-06, 5.22978598e-06,
        6.16048013e-09, 1.27954900e-06],
       [5.20551248e-06, 1.99746317e-10, 1.34672280e-06, 5.77114122e-07,
        9.97466445e-01, 2.14144779e-06, 8.58587737e-06, 7.88155303e-05,
        3.13840047e-07, 2.43644021e-03]], dtype=float32)